# This configuration is intended for development purposes — infrastructure only (no app container)
name: dev-gateway-service
services:
  sonar:
    extends:
      file: compose.base.yaml
      service: sonar

networks:
  gateway-service-network:
    name: iqkv-gateway-network-dev
    external: false
