# ===================================================================
# Spring Boot configuration for the "local" profile.
# ===================================================================

logging:
  level:
    com.iqkv: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${IAM_JWKS_URI:http://localhost:8080/.well-known/jwks.json}
